#!/usr/bin/env python3
"""Phase 1 analysis: reachability figure, empirical check, headline table, surprisal loci.

  python phase1_analysis.py --novelty artifacts/novelty_phase1 --cov_transfer 'artifacts/cov_base_transfer_k1e4.s*.jsonl' \
      --cov_val36 'artifacts/cov_base_val36_k1e5.s*.jsonl' --minlen_transfer artifacts/minlen_transfer.jsonl --out artifacts/phase1

Writes figures/phase1_*.png and <out>_*.md / .json tables.  All proof counts are start-index normalised.
"""
import argparse, json, math, glob, collections, os
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

BUDGETS = [512, 10000, 100000]
COL = {'2-4': '#9aa5b1', '5': '#7fb3d5', '6': '#2e86c1', '7': '#f39c12', '8': '#e74c3c', '9+': '#8e44ad'}


def rd(fn):
    return [json.loads(l) for l in open(fn) if l.strip()]


def rdglob(pat):
    out = []
    for fn in sorted(glob.glob(pat)):
        out += rd(fn)
    return out


def lbin(L):
    return '2-4' if L <= 4 else '5' if L == 5 else '6' if L == 6 else '7' if L == 7 else '8' if L == 8 else '9+'


def reach_table(items, key, title, lines):
    """items: list of (written_len, logp). Counts per length bin on each side of the budget lines."""
    by = collections.defaultdict(list)
    for L, lp in items:
        by[L].append(lp)
    rows = [f'### {title}', '', '| written length | n | ≥ 1/512 | 1/512 … 1/10⁴ | 1/10⁴ … 1/10⁵ | < 1/10⁵ | median log p |', '|---|---:|---:|---:|---:|---:|---:|']
    tot = collections.Counter()
    for L in sorted(by):
        v = by[L]
        c = [sum(x >= -math.log(512) for x in v), sum(-math.log(1e4) <= x < -math.log(512) for x in v),
             sum(-math.log(1e5) <= x < -math.log(1e4) for x in v), sum(x < -math.log(1e5) for x in v)]
        for i, x in enumerate(c):
            tot[i] += x
        rows.append(f'| {L} | {len(v)} | {c[0]} | {c[1]} | {c[2]} | {c[3]} | {np.median(v):.1f} |')
    n = sum(len(v) for v in by.values())
    rows.append(f'| all | {n} | {tot[0]} | {tot[1]} | {tot[2]} | {tot[3]} | |')
    lines += rows + ['']


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--novelty', default='artifacts/novelty_phase1')
    ap.add_argument('--cov_transfer', default='artifacts/cov_base_transfer_k1e4.s*.jsonl')
    ap.add_argument('--cov_val36', default='artifacts/cov_base_val36_k1e5.s*.jsonl')
    ap.add_argument('--minlen_transfer', default='artifacts/minlen_transfer.jsonl')
    ap.add_argument('--minlen_val36', default='artifacts/minlen_val36.jsonl')
    ap.add_argument('--out', default='artifacts/phase1')
    a = ap.parse_args()
    os.makedirs('figures', exist_ok=True)
    P = rd(a.novelty + '_proofs.jsonl')
    T = rd(a.novelty + '_theorems.jsonl')
    cov_t = {r['name']: r for r in rdglob(a.cov_transfer)}
    cov_v = {r['name']: r for r in rdglob(a.cov_val36)}
    ml_t = {r['name']: r for r in rd(a.minlen_transfer)} if os.path.exists(a.minlen_transfer) else {}
    ml_v = {r['name']: r for r in rd(a.minlen_val36)} if os.path.exists(a.minlen_val36) else {}
    md = ['# Phase 1 tables (generated by phase1_analysis.py)', '']
    md.append(f'Base-model coverage files: transfer {len(cov_t)} theorems, validation-36 {len(cov_v)} theorems.')
    md.append('')

    # ---------- 1. reachability tables ----------
    for src, title in (('final_transfer', 'Final-model (EI r16) transfer proofs'), ('final_targets', 'Final-model RL-target proofs'),
                       ('ei_allrounds_val36', 'EI validation-36 proofs (any round)'), ('frozen_transfer', 'Frozen Stage-1 transfer proofs (calibration)')):
        items = [(p['written'], p['base_logp_T08']) for p in P if p['src'] == src]
        reach_table(items, 'base_logp_T08', f'{title}: per proof, log p_base at T=0.8 marginalised over start index', md)
        items = [(t['min_written'], t['base_logp_T08_any']) for t in T if t['src'] == src]
        reach_table(items, 'any', f'{title}: per theorem (log of summed probability of all its found proofs; length = shortest found)', md)

    # ---------- 2. reachability figure ----------
    fig, axes = plt.subplots(1, 3, figsize=(16, 4.6))
    for ax, (src, title) in zip(axes, (('final_transfer', 'transfer (n=1,638), final model'), ('final_targets', 'RL targets (n=3,000), final model'),
                                         ('ei_allrounds_val36', 'validation-36, EI any round'))):
        items = [(p['written'], p['base_logp_T08']) for p in P if p['src'] == src]
        bins = np.arange(-160, 1, 4)
        groups = collections.OrderedDict((b, []) for b in COL)
        for L, lp in items:
            groups[lbin(L)].append(max(lp, -159))
        ax.hist([groups[b] for b in groups], bins=bins, stacked=True, color=[COL[b] for b in groups], label=[f'written {b}' for b in groups])
        for B, ls in zip(BUDGETS, (':', '--', '-')):
            ax.axvline(-math.log(B), color='k', ls=ls, lw=1)
            ax.text(-math.log(B) + 1, ax.get_ylim()[1] * 0.92, f'1/{B:g}', fontsize=8, rotation=90, va='top')
        ax.set_title(title, fontsize=10)
        ax.set_xlabel('log p_base(proof | prompt), T=0.8, start index marginalised')
        ax.set_xlim(-160, 2)
    axes[0].set_ylabel('distinct normalised proofs')
    axes[0].legend(fontsize=8, loc='upper left')
    plt.tight_layout()
    plt.savefig('figures/phase1_reachability.png', dpi=130)
    plt.close()

    # per-theorem version
    fig, axes = plt.subplots(1, 2, figsize=(11, 4.4))
    for ax, (src, title) in zip(axes, (('final_transfer', 'transfer: per theorem, any found proof'), ('final_targets', 'RL targets: per theorem, any found proof'))):
        items = [(t['min_written'], t['base_logp_T08_any']) for t in T if t['src'] == src]
        bins = np.arange(-160, 1, 4)
        groups = collections.OrderedDict((b, []) for b in COL)
        for L, lp in items:
            groups[lbin(L)].append(max(lp, -159))
        ax.hist([groups[b] for b in groups], bins=bins, stacked=True, color=[COL[b] for b in groups], label=[f'shortest found {b}' for b in groups])
        for B, ls in zip(BUDGETS, (':', '--', '-')):
            ax.axvline(-math.log(B), color='k', ls=ls, lw=1)
        ax.set_title(title, fontsize=10); ax.set_xlabel('log Σ p_base(found proofs | prompt), T=0.8'); ax.set_xlim(-160, 2)
    axes[0].set_ylabel('theorems'); axes[0].legend(fontsize=8, loc='upper left')
    plt.tight_layout(); plt.savefig('figures/phase1_reachability_theorems.png', dpi=130); plt.close()

    # ---------- 3. empirical check ----------
    if cov_t:
        # per theorem: predicted p (sum over RL-found proofs) vs measured rate n_ok/n_tried (all valid proofs)
        pred, meas, meas_found, names = [], [], [], []
        final_T = {t['name']: t for t in T if t['src'] == 'final_transfer'}
        final_P = collections.defaultdict(dict)
        for p in P:
            if p['src'] == 'final_transfer':
                final_P[p['name']][p['proof']] = p
        for name, c in cov_t.items():
            if name not in final_T:
                continue
            t = final_T[name]
            pred.append(t['base_logp_T08_any'])
            meas.append(c['n_ok'] / c['n_tried'])
            # rate of exactly the RL-found proofs
            cnt = {q['proof']: q['count'] for q in c['proofs']}
            meas_found.append(sum(cnt.get(pr, 0) for pr in final_P[name]) / c['n_tried'])
            names.append(name)
        pred = np.array(pred); meas = np.array(meas); meas_found = np.array(meas_found)
        k = cov_t[names[0]]['n_tried']
        fig, axes = plt.subplots(1, 2, figsize=(11, 5))
        floor = 0.3 / k
        for ax, m, title in zip(axes, (meas_found, meas), ('measured rate of exactly the RL-found proofs', 'measured rate of ANY verified proof')):
            mm = np.maximum(m, floor)
            ax.scatter(np.exp(pred), mm, s=6, alpha=0.5, c=['#e74c3c' if x == 0 else '#2e86c1' for x in m])
            ax.plot([1e-30, 1], [1e-30, 1], 'k--', lw=1)
            ax.axhline(1 / k, color='gray', ls=':', lw=1); ax.text(1e-29, 1.3 / k, f'1 hit in {k:g}', fontsize=8)
            ax.set_xscale('log'); ax.set_yscale('log'); ax.set_xlim(1e-30, 2); ax.set_ylim(floor * 0.7, 2)
            ax.set_xlabel('predicted: Σ p_base(RL-found proofs), T=0.8'); ax.set_ylabel(title)
            ax.set_title(f'{title}\n(red = 0 hits in {k:g} samples, plotted at the floor)', fontsize=9)
        plt.tight_layout(); plt.savefig('figures/phase1_empirical_check.png', dpi=130); plt.close()
        # calibration numbers on the well-measured range (predicted >= 10/k)
        sel = pred >= math.log(10 / k)
        if sel.sum():
            ratio = np.log(np.maximum(meas_found[sel], floor)) - pred[sel]
            md.append(f'Empirical check (transfer, k={k:g}): theorems with predicted rate ≥ 10/k: {int(sel.sum())}; '
                      f'median log(measured/predicted) for exactly the RL-found proofs = {np.median(ratio):.2f} nats; '
                      f'Spearman-free summary: fraction within a factor of 3: {np.mean(np.abs(ratio) < math.log(3)):.2f}.')
        # theorems predicted unreachable but measured reachable (other proofs exist)
        unreach = pred < -math.log(k)
        md.append(f'Theorems whose RL-found proofs have predicted total p < 1/k: {int(unreach.sum())}; of those the base model solved '
                  f'(any proof) within k samples: {int((meas[unreach] > 0).sum())}.')
        md.append('')

        # ---------- 4. headline table ----------
        md.append('## Headline: transfer theorems solved by RL (EI r16, 512 attempts) that the base model did NOT solve in 10⁴ samples')
        md.append('')
        rows = []
        for name in names:
            c = cov_t[name]
            if c['n_ok'] > 0:
                continue
            t = final_T[name]
            m = ml_t.get(name, {})
            rows.append((t['base_logp_T08_any'], name, t['thm'], t['min_written'], t['n_proofs'], t['first_round'], m.get('min_lines_ub'), t['gen_lines']))
        rows.sort()
        solved_final = len(names)
        md.append(f'{len(rows)} of the {solved_final} final-solved transfer theorems with coverage data are unsolved by the base in 10⁴ samples '
                  f'({len(cov_t)} of 1,638 transfer theorems have coverage data so far).')
        md.append('')
        by_len = collections.Counter(r[3] for r in rows)
        md.append('By shortest RL-found written length: ' + ', '.join(f'{L}: {by_len[L]}' for L in sorted(by_len)))
        by_ml = collections.Counter(str(r[6]) for r in rows)
        md.append('By minlen label (min_lines_ub, None = no ≤8-line proof found): ' + ', '.join(f'{L}: {by_ml[L]}' for L in sorted(by_ml)))
        md.append('')
        md.append('| log p_base(any found), T=0.8 | theorem | shortest RL proof | # RL proofs | first round | min_lines_ub | gen length |')
        md.append('|---:|---|---:|---:|---:|---:|---:|')
        for r in rows[:40]:
            md.append(f'| {r[0]:.1f} | `{r[2]}` | {r[3]} | {r[4]} | {r[5]} | {r[6]} | {r[7]} |')
        if len(rows) > 40:
            md.append(f'| … | ({len(rows) - 40} more in {a.out}_unsolved_by_base.jsonl) | | | | | |')
        with open(a.out + '_unsolved_by_base.jsonl', 'w') as f:
            for r in rows:
                f.write(json.dumps({'base_logp_T08_any': r[0], 'name': r[1], 'thm': r[2], 'min_written': r[3], 'n_proofs': r[4], 'first_round': r[5], 'min_lines_ub': r[6], 'gen_lines': r[7]}) + '\n')
        md.append('')
        # pass@B summary of the base model on the transfer set
        for B in (32, 128, 512, 1000, 10000):
            n = sum(c['solved_within'][str(B)] for c in cov_t.values())
            md.append(f'- base model, transfer, solved within {B:g} samples: {n}/{len(cov_t)}')
        md.append(f'- final model (EI r16, 512 attempts): {len(final_T)}/1638 solved; overlap with coverage data: {solved_final}')
        md.append('')

    if cov_v:
        md.append('## Validation-36: base model at k = 10⁵ vs EI')
        md.append('')
        md.append('| theorem | bin | ref lines | base n_ok / 10⁵ | first hit | EI solved (any round) | log p_base(EI proofs) T=0.8 | EI shortest |')
        md.append('|---|---|---:|---:|---:|---|---:|---:|')
        ei = {t['name']: t for t in T if t['src'] == 'ei_allrounds_val36'}
        val = {r['name']: r for r in rd('targets/validation_36.jsonl')}
        for name, c in cov_v.items():
            v = val[name]; e = ei.get(name)
            md.append(f"| {name} | {v['bin']} | {v['min_lines_ub']} | {c['n_ok']} | {c['first_hit']} | {'yes' if e else 'no'} | "
                      f"{e['base_logp_T08_any']:.1f} | {e['min_written']} |" if e else
                      f"| {name} | {v['bin']} | {v['min_lines_ub']} | {c['n_ok']} | {c['first_hit']} | no | | |")
        md.append('')

    # ---------- 5. surprisal loci ----------
    md.append('## Where the novelty sits: surprisal locus of improbable RL-found proofs (base model, T=1, best start index)')
    md.append('')
    for src in ('final_transfer', 'final_targets'):
        imp = [p for p in P if p['src'] == src and p['base_logp_T08'] < -math.log(1e5)]
        md.append(f'### {src}: {len(imp)} proofs with p_base < 1/10⁵')
        md.append('')
        c = collections.Counter(p['base_max_line_rule'] for p in imp)
        md.append('rule at the max-surprisal line: ' + ', '.join(f'{k} {v}' for k, v in c.most_common()))
        c = collections.Counter(p['base_max_tok'] for p in imp)
        md.append('max-surprisal token: ' + ', '.join(f'`{k}` {v}' for k, v in c.most_common(10)))
        sh = np.array([p['base_max_line_share'] for p in imp])
        nl = collections.Counter(sum(1 for v in p['base_line_surprisal'] if v > 3) for p in imp)
        md.append(f'share of the proof\'s surprisal in its max line: median {np.median(sh):.2f}, ≥ 0.5 in {np.mean(sh >= 0.5):.0%}; '
                  f'number of lines with > 3 nats: ' + ', '.join(f'{k}: {v}' for k, v in sorted(nl.items())))
        pos = collections.Counter('first' if p['base_max_line'] == 1 else 'last' if p['base_max_line'] == p['written'] else 'middle' for p in imp)
        md.append('position of the max line: ' + ', '.join(f'{k} {v}' for k, v in pos.items()))
        md.append('')
        md.append('| written | n | max-line rule (top 4) |')
        md.append('|---:|---:|---|')
        for L in sorted({p['written'] for p in imp}):
            cc = collections.Counter(p['base_max_line_rule'] for p in imp if p['written'] == L)
            md.append(f'| {L} | {sum(cc.values())} | ' + ', '.join(f'{k} {v}' for k, v in cc.most_common(4)) + ' |')
        md.append('')
    # five examples: transfer proofs the base did not solve at 1e4 (if available), longest first
    md.append('### Five examples (transfer; base did not solve the theorem in 10⁴ samples where coverage data exists), per-line surprisal in nats')
    md.append('')
    ex = [p for p in P if p['src'] == 'final_transfer' and p['written'] >= 8 and (not cov_t or (p['name'] in cov_t and cov_t[p['name']]['n_ok'] == 0))]
    ex.sort(key=lambda p: (-p['written'], p['base_logp_T08']))
    seen = set(); shown = 0
    for p in ex:
        if p['name'] in seen:
            continue
        seen.add(p['name']); shown += 1
        md.append(f"**{p['thm']}** — written {p['written']}, pruned {p['pruned']}, log p_base(T=0.8) = {p['base_logp_T08']:.1f}, log p_final = {p['final_logp_T08']:.1f}, "
                  f"max-surprisal line {p['base_max_line']} ({p['base_max_line_rule']}), first found round {p['round']}")
        md.append('```')
        for ln, s in zip(p['proof'].split(' ; '), p['base_line_surprisal']):
            md.append(f'{s:7.2f}  {ln}')
        md.append('```')
        if shown >= 5:
            break
    open(a.out + '_tables.md', 'w').write('\n'.join(md) + '\n')
    print('\n'.join(md[:60]))
    print('...\nwrote', a.out + '_tables.md')


if __name__ == '__main__':
    main()
