#!/usr/bin/env python3
"""search-expert analysis: every count from the pulled files (artifacts/sx/).  Torch-free; run on the VPS.

  python3 sx_analysis.py [--dir artifacts/sx] [--out artifacts/sx/analysis]      -> <out>.md, <out>.json

Arms (state_ladder_ei.py outdirs): A_s<S> (sampling expert), B_s<S> (best-first search expert, budgets = A's per-target
actions), A2_s<S> (A re-drawn: --seed_offset 50), C_s<S> (truncate-and-resume, budgets = A2's actions).
Read-outs (no search): rr/<arm>__l2.jsonl (the 91 = transfer_long2 + calibration) and rr/<arm>__rr1316.jsonl (rr600
L_true 13-16), lpool_reread.py rows (name, solved, proofs, written_lens).
Primary Q (pre-registered): solved of the 91 + rr600 generator theorems at L_true 15-16 (291).
"""
import argparse, collections, json, os, random, statistics as stt, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

SEEDS = range(6)
T975 = {1: 12.706, 2: 4.303, 3: 3.182, 4: 2.776, 5: 2.571}
T80 = {1: 1.376, 2: 1.061, 3: 0.978, 4: 0.941, 5: 0.920}


def rd(fn):
    return [json.loads(l) for l in open(fn) if l.strip()]


def iqm(xs):
    xs = sorted(xs); n = len(xs)
    if n < 4:
        return sum(xs) / n
    lo, hi = n / 4, 3 * n / 4           # interquartile mean with fractional end weights
    tot = w = 0.0
    for i, x in enumerate(xs):
        a, b = max(i, lo), min(i + 1, hi)
        if b > a:
            tot += x * (b - a); w += b - a
    return tot / w


def boot_ci(xs, f=iqm, n=10000, seed=0):
    r = random.Random(seed)
    v = sorted(f([r.choice(xs) for _ in xs]) for _ in range(n))
    return v[int(0.025 * n)], v[int(0.975 * n) - 1]


def load_reads(d, arm):
    out = {}
    for part in ('l2', 'rr1316'):
        fn = f'{d}/rr/{arm}__{part}.jsonl'
        if not os.path.exists(fn):
            return None
        for r in rd(fn):
            out[r['name']] = r
    return out


def pools():
    l2 = rd('data/ladder/transfer_long2_91.jsonl')
    rr = rd('data/ladder/rr600_13to16.jsonl')
    strata = {r['name']: ('l2_17' if r['stratum'] == '17' else 'l2_ge18') for r in l2}
    for r in rr:
        strata[r['name']] = f"rr{r['L_true_lb']}{'' if r['source'] == 'gen' else '_tb'}"
    Q = {n for n, s in strata.items() if s in ('l2_17', 'l2_ge18', 'rr15', 'rr16')}
    return strata, Q


def expert_rounds(d, arm, rounds=8):
    """per round: accepted-this-round target set (from alloc cumulative accepted counts), actions, stats."""
    out = []
    prev = collections.Counter()
    for r in range(1, rounds + 1):
        fa = f'{d}/{arm}/alloc_{r}.json'
        fr = f'{d}/{arm}/round_{r}.json'
        if not (os.path.exists(fa) and os.path.exists(fr)):
            break
        al = json.load(open(fa)); st = json.load(open(fr))
        acc = collections.Counter(al['accepted'])
        solved_r = {t for t in acc if acc[t] - prev[t] > 0}
        prev = acc
        out.append({'round': r, 'solved': solved_r, 'actions': st.get('actions'), 'budget': st.get('budget_actions'),
                    'cum_solved': st['targets_cum']['solved'], 'secs': st.get('secs'), 'env': st.get('env', {}),
                    'mix_rl': st.get('mix_rl_records')})
    return out


def found_first(d, arm, r):
    """target -> shortest found proof (written, tokens) among found_<r>.jsonl"""
    fn = f'{d}/{arm}/found_{r}.jsonl'
    best = {}
    if not os.path.exists(fn):
        return best
    for x in rd(fn):
        k = (x['written'], len(x['proof'].split()))
        if x['name'] not in best or k < best[x['name']]:
            best[x['name']] = k
    return best


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--dir', default='artifacts/sx'); ap.add_argument('--out', default='artifacts/sx/analysis')
    a = ap.parse_args()
    d = a.dir
    strata, Q = pools()
    res = {'Q_n': len(Q), 'reads': {}, 'paired': {}, 'rounds': {}}
    md = ['# search-expert analysis (generated by sx_analysis.py; every count from artifacts/sx/)', '']
    # ---------------- read-outs
    reads = {}
    for arm in ('A', 'B', 'A2', 'C'):
        for s in SEEDS:
            x = load_reads(d, f'{arm}_s{s}')
            if x is not None:
                reads[(arm, s)] = x
    strat_names = ['l2_17', 'l2_ge18', 'rr15', 'rr16', 'rr13', 'rr14']
    md += ['## Read-out without search (k 256, T 0.8, max_steps 96): theorems solved', '',
           '| arm | seed | **Q (/291)** | 17 (/61) | ≥ 18 (/30) | rr 15 (/100) | rr 16 (/100) | rr 13 (/90) | rr 14 (/90) | textbook 13–14 (/20) |',
           '|---|---|---:|---:|---:|---:|---:|---:|---:|---:|']
    for (arm, s), x in sorted(reads.items()):
        c = collections.Counter(strata[n] for n, r in x.items() if r['solved'])
        q = sum(1 for n in Q if x.get(n, {}).get('solved'))
        tb = c['rr13_tb'] + c['rr14_tb']
        res['reads'][f'{arm}_s{s}'] = {'Q': q, **{k: c[k] for k in strat_names}, 'textbook': tb}
        md.append(f'| {arm} | {s} | **{q}** | ' + ' | '.join(str(c[k]) for k in strat_names) + f' | {tb} |')
    md.append('')
    # ---------------- same-checkpoint spread and MDD
    same = [(s, res['reads'][f'A_s{s}']['Q'], res['reads'][f'A2_s{s}']['Q']) for s in SEEDS
            if f'A_s{s}' in res['reads'] and f'A2_s{s}' in res['reads']]
    if same:
        sd_same = (sum((q1 - q2) ** 2 / 2 for _, q1, q2 in same) / len(same)) ** 0.5
        flips = []
        for s, _, _ in same:
            x1, x2 = reads[('A', s)], reads[('A2', s)]
            flips.append(sum(1 for n in Q if bool(x1[n]['solved']) != bool(x2[n]['solved'])))
        res['same_ckpt'] = {'pairs': same, 'sd_same': sd_same, 'per_theorem_flips_Q': flips}
        md += ['## Same-checkpoint spread (A vs A2: same Stage-1 checkpoint, re-drawn ladder)', '',
               f'Q A / A2 per seed: {", ".join(f"s{s} {q1} / {q2}" for s, q1, q2 in same)}; s = RMS((A−A2)/√2) = **{sd_same:.1f}**; '
               f'theorems of Q solved by exactly one of the two: {flips}.', '']
    # ---------------- paired comparisons
    for comp in (('B', 'A'), ('C', 'A'), ('C', 'A2'), ('A2', 'A')):
        x, y = comp
        diffs, disc = [], []
        for s in SEEDS:
            if (x, s) in reads and (y, s) in reads:
                qx = res['reads'][f'{x}_s{s}']['Q']; qy = res['reads'][f'{y}_s{s}']['Q']
                rx, ry = reads[(x, s)], reads[(y, s)]
                only_x = sum(1 for n in Q if rx[n]['solved'] and not ry[n]['solved'])
                only_y = sum(1 for n in Q if ry[n]['solved'] and not rx[n]['solved'])
                diffs.append((s, qx - qy)); disc.append((s, only_x, only_y))
        if not diffs:
            continue
        ds = [v for _, v in diffs]
        n = len(ds)
        entry = {'per_seed': diffs, 'discordant': disc, 'mean': sum(ds) / n}
        if n >= 2:
            sd_d = stt.stdev(ds)
            entry['sd_diff'] = sd_d
            entry['mdd_from_sd_diff'] = (T975[n - 1] + T80[n - 1]) / n ** 0.5 * sd_d
            if 'same_ckpt' in res:
                entry['mdd_from_same_ckpt'] = (T975[n - 1] + T80[n - 1]) / n ** 0.5 * 2 ** 0.5 * res['same_ckpt']['sd_same']
            entry['iqm'] = iqm(ds); entry['iqm_ci95'] = boot_ci(ds)
            entry['t'] = (sum(ds) / n) / (sd_d / n ** 0.5) if sd_d > 0 else None
        res['paired'][f'{x}-{y}'] = entry
        md += [f'## Paired {x} − {y} on Q (per seed)', '',
               f'Per seed: {", ".join(f"s{s} {v:+d}" for s, v in diffs)}; mean {entry["mean"]:+.1f}' +
               (f'; IQM {entry["iqm"]:+.1f} [95 % CI {entry["iqm_ci95"][0]:+.1f}, {entry["iqm_ci95"][1]:+.1f}]; sd {entry["sd_diff"]:.1f}; '
                f'MDD (from this sd) {entry["mdd_from_sd_diff"]:.1f}' if n >= 2 else '') +
               (f'; MDD (from same-checkpoint s) {entry["mdd_from_same_ckpt"]:.1f}' if 'mdd_from_same_ckpt' in entry else '') + '.',
               f'Discordant theorems (only {x} / only {y}): {", ".join(f"s{s} {a_}/{b_}" for s, a_, b_ in disc)}.', '']
    # ---------------- experts per round
    md += ['## The experts, per round (training targets, 4,495)', '',
           '| seed | arm | round | actions | budget | solved this round | new cum. solved | past other arm (solved now, never by the other in rounds ≤ r) |',
           '|---|---|---:|---:|---:|---:|---:|---:|']
    for s in SEEDS:
        for x, y in (('B', 'A'), ('A', 'B'), ('C', 'A2'), ('A2', 'C')):
            ex, ey = expert_rounds(d, f'{x}_s{s}'), expert_rounds(d, f'{y}_s{s}')
            if not ex or not ey:
                continue
            seen_y = set()
            rows = []
            for rx, ry in zip(ex, ey):
                seen_y |= ry['solved']
                past = len(rx['solved'] - seen_y)
                rows.append({'round': rx['round'], 'actions': rx['actions'], 'budget': rx['budget'], 'solved': len(rx['solved']),
                             'cum_solved': rx['cum_solved'], 'past_other': past, 'secs': rx['secs']})
                md.append(f"| {s} | {x} (vs {y}) | {rx['round']} | {rx['actions']} | {rx['budget'] or ''} | {len(rx['solved'])} | {rx['cum_solved']} | {past} |")
            res['rounds'][f'{x}_s{s}_vs_{y}'] = rows
    md.append('')
    # ---------------- lengths of the training proofs (shortest per target, final round)
    md += ['## Shortest found proof per target (final found file): lines', '',
           '| seed | arm pair | targets both solved | median lines x / y | x shorter / equal / longer |', '|---|---|---:|---|---|']
    for s in SEEDS:
        for x, y in (('B', 'A'), ('C', 'A2')):
            fx, fy = found_first(d, f'{x}_s{s}', 8), found_first(d, f'{y}_s{s}', 8)
            both = sorted(set(fx) & set(fy))
            if not both:
                continue
            lx = [fx[n][0] for n in both]; ly = [fy[n][0] for n in both]
            sh = sum(1 for n in both if fx[n][0] < fy[n][0]); eq = sum(1 for n in both if fx[n][0] == fy[n][0])
            res.setdefault('lengths', {})[f'{x}-{y}_s{s}'] = {'n': len(both), 'median_x': stt.median(lx), 'median_y': stt.median(ly),
                                                             'shorter': sh, 'equal': eq, 'longer': len(both) - sh - eq}
            md.append(f'| {s} | {x} vs {y} | {len(both)} | {stt.median(lx)} / {stt.median(ly)} | {sh} / {eq} / {len(both) - sh - eq} |')
    open(a.out + '.md', 'w').write('\n'.join(md) + '\n')
    json.dump(res, open(a.out + '.json', 'w'), indent=1, default=list)
    print('\n'.join(md))


if __name__ == '__main__':
    main()
