"""Merge the per-part experiment maps (atlas/raw/{A..E}_map.csv) into atlas/data/experiment_map.csv.

Adds `checker_class` (lean_only / lean_and_ndverify / nd_verify / old_nd_verifier / mixed / n/a) and
`area_primary`; sorts by area, then date. Prints counts per area and per checker class."""
import csv, collections, os, sys
RAW = os.path.join(os.path.dirname(__file__), '..', 'raw')
OUT = os.path.join(os.path.dirname(__file__), '..', 'data', 'experiment_map.csv')
AREAS = ['create_vs_elicit', 'data_caps', 'format', 'pretrain_recipe', 'rl_algorithm', 'interface',
         'search_exploration', 'measurement', 'llm_pretrained', 'infrastructure', 'other']

def checker_class(c):
    c = c.strip()
    if c in ('lean_only', 'lean_and_ndverify', 'nd_verify', 'n/a', ''):
        return c or 'n/a'
    if '/' in c or ';' in c or '+' in c:
        return 'mixed'
    if c.startswith('other:nd2lean'):
        return 'lean_and_ndverify' if 'nd_verify' in c else 'lean(nd2lean)'
    if c.startswith('lean_check'):
        return 'lean_only'
    if 'verif' in c.lower():
        return 'old_nd_verifier'
    return 'other'

rows = []
for p in 'ABCDE':
    f = os.path.join(RAW, f'{p}_map.csv')
    if not os.path.exists(f):
        print('missing', f, file=sys.stderr); continue
    for r in csv.DictReader(open(f)):
        r['part'] = p
        r['area_primary'] = r['area'].split(';')[0].strip()
        assert r['area_primary'] in AREAS, (p, r['id'], r['area'])
        r['checker_class'] = checker_class(r['checker'])
        rows.append(r)
ids = collections.Counter(r['id'] for r in rows)
assert all(v == 1 for v in ids.values()), [k for k, v in ids.items() if v > 1]
rows.sort(key=lambda r: (AREAS.index(r['area_primary']), r['date'], r['id']))
cols = ['id', 'date', 'area_primary', 'area', 'title', 'owner', 'model', 'params', 'format', 'init', 'train_set', 'cap',
        'protocol', 'checker', 'checker_class', 'headline', 'review_status', 'source', 'part']
with open(OUT, 'w', newline='') as fh:
    w = csv.DictWriter(fh, fieldnames=cols); w.writeheader(); w.writerows(rows)
print('rows', len(rows))
for k, v in collections.Counter(r['area_primary'] for r in rows).most_common(): print(f'  {k:20s} {v}')
for k, v in collections.Counter(r['checker_class'] for r in rows).most_common(): print(f'  {k:20s} {v}')
for k, v in collections.Counter(r['owner'] for r in rows).most_common(): print(f'  {k:20s} {v}')

# ---- atlas/MAP.md: the full map as a readable table, one section per question ----
TITLES = {'create_vs_elicit': 'Create vs elicit', 'data_caps': 'Data and caps', 'format': 'Format',
          'pretrain_recipe': 'Pretraining recipe', 'rl_algorithm': 'RL algorithm', 'interface': 'Interface (whole proof vs proof state)',
          'search_exploration': 'Search and exploration', 'measurement': 'Measurement (noise, judges, metrics)',
          'llm_pretrained': 'Pretrained LLMs', 'infrastructure': 'Infrastructure', 'other': 'Other'}
CK = {'lean_only': 'Lean', 'lean_and_ndverify': 'Lean∧ndv', 'nd_verify': 'ndv', 'old_nd_verifier': 'old ND', 'mixed': 'mixed',
      'n/a': '—', 'lean(nd2lean)': 'Lean (nd2lean)', 'other': 'other'}


def cell(x, n=None):
    x = ' '.join((x or '').split()).replace('|', '/')
    return x if n is None or len(x) <= n else x[:n - 1] + '…'


def link(src):
    parts = src.split(':', 2)
    if len(parts) == 3 and parts[0] in ('nd-rl', 'fork'):
        return f'{parts[0]} `{parts[1]}`: `{parts[2]}`'
    return cell(src)


MD = os.path.join(os.path.dirname(__file__), '..', 'MAP.md')
with open(MD, 'w') as fh:
    fh.write('# Experiment map (generated by `atlas/scripts/build_map.py` from `atlas/data/experiment_map.csv`)\n\n'
             'One row per experiment. Checker: Lean = Lean alone; Lean∧ndv = Lean ∧ nd_verify; ndv = nd_verify alone; '
             'old ND = pre-`nd_verify` verifiers. Review: R = reviewed, R! = reviewed with result-changing findings, '
             'U = unreviewed. Headlines are copied from the source and carry its caveats; the source is the link.\n')
    for a in AREAS:
        rs = [r for r in rows if r['area_primary'] == a]
        if not rs:
            continue
        fh.write(f'\n## {TITLES[a]} ({len(rs)})\n\n| date | id | owner | model | checker | review | headline | source |\n'
                 '|---|---|---|---|---|---|---|---|\n')
        for r in rs:
            rv = {'reviewed': 'R', 'reviewed-findings': 'R!', 'unreviewed': 'U'}.get(r['review_status'], '—')
            fh.write(f"| {r['date']} | {r['id']} | {r['owner']} | {cell(r['model'], 70)} ({cell(r['params'])}, "
                     f"{cell(r['format'])}) | {CK.get(r['checker_class'], r['checker_class'])} | {rv} | "
                     f"{cell(r['headline'], 260)} | {link(r['source'])} |\n")
print('wrote', os.path.normpath(MD))
